node {
   def commit_id
   def nodejs_docker_name = 'bennyleder/docker-nodejs-demo'
   stage('step pre') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       dir("basics"){
       sh 'npm install --only=dev'
       sh 'npm test'
       }
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'bennyl_dockerhub') {
       def app = docker.build("yanivomc/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
   stage('docker run') {
   
      docker run --rm -tid --name docker_test -p 3000 ${nodejs_docker_name }:${commit_id}
      docker kill docker_test
      
      '''
     }
   }

